---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind1
nodes:
- role: control-plane
  kubeadmConfigPatches:
    - |
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      # networking:
      #   dnsDomain: "cluster.kind1"
# - role:  worker                                                                                                                                                                                         
# - role:  worker                                                                                                                                                                                         

